---
#- name: Include OS family specific variables
#  include_vars: "{{ ansible_os_family }}.yml"

- name: 'Redhat | Add offical mongodb yum repository'
  yum_repository:
    name: "mongodb-org-{{ mongodb_version }}"
    baseurl: "https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/{{ mongodb_version }}/x86_64/"
    description: MongoDB Repository
    gpgcheck: yes
    gpgkey: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"
    state: present
  when: ansible_os_family == "RedHat"

- name: 'Debian | Add offical mongodb apt key'
  apt_key:
    id: "{{ mongodb_apt_key }}"
    keyserver: "{{ mongodb_apt_keyserver }} "
    state: present
  when: ansible_os_family == "Debian"



- name: 'Debian | Add offical mongodb repository'
  apt_repository:
    repo: "deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/{{ mongodb_version }} multiverse"
    update_cache: yes
    state: present
  when: ansible_os_family == "Debian"

- name: 'Common | Install the mongodb'
  package:
    name: mongodb-org
    state: present

- name: 'Common | Create the mongodb dbPath directory'
  file:
    path: "{{ mongodb_db_path }}"
    state: directory
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_group }}"
    mode: 0755

- name: 'Common | Populate pre mongod config file'
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: 0644
  notify: restart mongod

- name: 'Common | Ensure mongodb is started and enabled on boot'
  service:
    name: mongod
    state: started
    enabled: yes

- name: 'CONFIG | Manage services'
  become: True
  include: manage_services.yml

- name: 'Debian | Install PyMongo'
  include: pymongo.debian.yml
  when: ansible_os_family == "Debian"


- name: 'RedHat | Install PyMongo'
  include: pymongo.redhat.yml
  when: ansible_os_family == "RedHat"

- import_tasks: user_and_db.yml 
  tags:
    - database
