---
- name: 'CONFIG | HUGEPAGE SERVICE | Create service file'
  template:
    src: "{{ role_path }}/templates/services/initd_hugepage.j2"
    dest: "/etc/init.d/disable-transparent-hugepages"
    owner: 'root'
    group: 'root'
    mode: '0700'
  register: 'mongodb_check_hugepage_service_file'
  when: 'mongodb_manage_hugepage_settings'

- name: 'CONFIG | HUGEPAGE SERVICE | Manage service settings with Ansible != 2.2'
  service:
    name: 'disable-transparent-hugepages'
    state: 'started'
    enabled: True
  register: 'mongodb_check_hugepage_service_state'
  when:
    - 'mongodb_manage_hugepage_settings'
    - "((ansible_version.full | version_compare('2.2', '<'))
          or (ansible_version.full | version_compare('2.3', '>=')))"


- name: 'CONFIG | HUGEPAGE SERVICE | Manage service settings with Ansible == 2.2'
  service:
    name: 'disable-transparent-hugepages'
    state: 'started'
    enabled: True
    use: 'service'
  register: 'mongodb_check_hugepage_service_state'
  when:
    - 'mongodb_manage_hugepage_settings'
    - "ansible_version.full | version_compare('2.2', '>=')"
    - "ansible_version.full | version_compare('2.3', '<')"

