---
- name: 'Debian | Install PyMongo package'
  apt: pkg=python-pymongo state=latest
  when: not mongodb_pymongo_from_pip

- name: 'Debian | Install PIP'
  apt: pkg={{ item }}
  with_items:
    - python-dev
    - python-pip
  when: mongodb_pymongo_from_pip

- name: 'Debian | Install PyMongo from PIP'
  pip: name=pymongo state=latest
  when: mongodb_pymongo_from_pip
